spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subvert?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456